In [30]:
import numpy as np
import pandas as pd


In [31]:
df = pd.read_csv("../dataset/WA_Fn-UseC_-Telco-Customer-Churn.csv")

In [32]:
df=df.drop(columns=['customerID'])

In [33]:
df['TotalCharges'].unique()

array(['29.85', '1889.5', '108.15', ..., '346.45', '306.6', '6844.5'],
      dtype=object)

In [34]:
df['TotalCharges']=pd.to_numeric(df['TotalCharges'],errors='coerce')

In [35]:
df['TotalCharges'].unique()

array([  29.85, 1889.5 ,  108.15, ...,  346.45,  306.6 , 6844.5 ])

In [36]:
df['TotalCharges'].isnull().sum()

11

In [37]:
df['TotalCharges']=df['TotalCharges'].fillna(0)

In [38]:
df['TotalCharges'].isnull().sum()

0

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   gender            7043 non-null   object 
 1   SeniorCitizen     7043 non-null   int64  
 2   Partner           7043 non-null   object 
 3   Dependents        7043 non-null   object 
 4   tenure            7043 non-null   int64  
 5   PhoneService      7043 non-null   object 
 6   MultipleLines     7043 non-null   object 
 7   InternetService   7043 non-null   object 
 8   OnlineSecurity    7043 non-null   object 
 9   OnlineBackup      7043 non-null   object 
 10  DeviceProtection  7043 non-null   object 
 11  TechSupport       7043 non-null   object 
 12  StreamingTV       7043 non-null   object 
 13  StreamingMovies   7043 non-null   object 
 14  Contract          7043 non-null   object 
 15  PaperlessBilling  7043 non-null   object 
 16  PaymentMethod     7043 non-null   object 


In [40]:
df=pd.get_dummies(df,columns=['Contract','PaymentMethod','InternetService'] ,drop_first=True)

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 24 columns):
 #   Column                                 Non-Null Count  Dtype  
---  ------                                 --------------  -----  
 0   gender                                 7043 non-null   object 
 1   SeniorCitizen                          7043 non-null   int64  
 2   Partner                                7043 non-null   object 
 3   Dependents                             7043 non-null   object 
 4   tenure                                 7043 non-null   int64  
 5   PhoneService                           7043 non-null   object 
 6   MultipleLines                          7043 non-null   object 
 7   OnlineSecurity                         7043 non-null   object 
 8   OnlineBackup                           7043 non-null   object 
 9   DeviceProtection                       7043 non-null   object 
 10  TechSupport                            7043 non-null   object 
 11  Stre

In [42]:
category_column=['gender','Partner','Dependents','PhoneService','MultipleLines','OnlineSecurity','OnlineBackup','DeviceProtection','TechSupport','StreamingTV','StreamingMovies','PaperlessBilling','Churn']

In [43]:
df[category_column]=df[category_column].replace({
    'Yes': 1,
    'No': 0,
    'No internet service': 0,
    'No phone service': 0,
    'Male': 0,
    'Female':1,
})

C:\Users\kavya\AppData\Local\Temp\ipykernel_22468\3915383950.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[category_column]=df[category_column].replace({


In [44]:
df

gender  SeniorCitizen  Partner  Dependents  tenure  PhoneService  \
0          1              0        1           0       1             0   
1          0              0        0           0      34             1   
2          0              0        0           0       2             1   
3          0              0        0           0      45             0   
4          1              0        0           0       2             1   
...      ...            ...      ...         ...     ...           ...   
7038       0              0        1           1      24             1   
7039       1              0        1           1      72             1   
7040       1              0        1           1      11             0   
7041       0              1        1           0       4             1   
7042       0              0        0           0      66             1   

      MultipleLines  OnlineSecurity  OnlineBackup  DeviceProtection  ...  \
0                 0               0             1                 0  ...   
1                 0               1             0                 1  ...   
2                 0               1             1                 0  ...   
3                 0               1             0                 1  ...   
4                 0               0             0                 0  ...   
...             ...             ...           ...               ...  ...   
7038              1               1             0                 1  ...   
7039              1               0             1                 1  ...   
7040              0               1             0                 0  ...   
7041              1               0             0                 0  ...   
7042              0               1             0                 1  ...   

      MonthlyCharges  TotalCharges  Churn  Contract_One year  \
0              29.85         29.85      0              False   
1              56.95       1889.50      0               True   
2              53.85        108.15      1              False   
3              42.30       1840.75      0               True   
4              70.70        151.65      1              False   
...              ...           ...    ...                ...   
7038           84.80       1990.50      0               True   
7039          103.20       7362.90      0               True   
7040           29.60        346.45      0              False   
7041           74.40        306.60      1              False   
7042          105.65       6844.50      0              False   

      Contract_Two year  PaymentMethod_Credit card (automatic)  \
0                 False                                  False   
1                 False                                  False   
2                 False                                  False   
3                 False                                  False   
4                 False                                  False   
...                 ...                                    ...   
7038              False                                  False   
7039              False                                   True   
7040              False                                  False   
7041              False                                  False   
7042               True                                  False   

      PaymentMethod_Electronic check  PaymentMethod_Mailed check  \
0                               True                       False   
1                              False                        True   
2                              False                        True   
3                              False                       False   
4                               True                       False   
...                              ...                         ...   
7038                           False                        True   
7039                           False                       False   
7040                          

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 24 columns):
 #   Column                                 Non-Null Count  Dtype  
---  ------                                 --------------  -----  
 0   gender                                 7043 non-null   int64  
 1   SeniorCitizen                          7043 non-null   int64  
 2   Partner                                7043 non-null   int64  
 3   Dependents                             7043 non-null   int64  
 4   tenure                                 7043 non-null   int64  
 5   PhoneService                           7043 non-null   int64  
 6   MultipleLines                          7043 non-null   int64  
 7   OnlineSecurity                         7043 non-null   int64  
 8   OnlineBackup                           7043 non-null   int64  
 9   DeviceProtection                       7043 non-null   int64  
 10  TechSupport                            7043 non-null   int64  
 11  Stre

In [46]:
from sklearn.model_selection import train_test_split

X = df.drop('Churn',axis=1)
y =df['Churn']

X_train , X_test , y_train , y_test = train_test_split(
    X,y,
    test_size=0.2,
    random_state=42,
)

In [47]:
X_train.shape , X_test.shape

((5634, 23), (1409, 23))

In [48]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter=1000)
model.fit(X_train,y_train)

A:\New folder\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(max_iter=1000)

In [49]:
from sklearn.metrics import accuracy_score
y_pred=model.predict(X_test)
accuracy_score(y_test,y_pred)


0.8211497515968772

In [50]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[933, 103],
       [149, 224]], dtype=int64)

In [51]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.86      0.90      0.88      1036
           1       0.69      0.60      0.64       373

    accuracy                           0.82      1409
   macro avg       0.77      0.75      0.76      1409
weighted avg       0.82      0.82      0.82      1409



In [56]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=200,random_state=42)
model.fit(X_train,y_train)

RandomForestClassifier(n_estimators=200, random_state=42)

In [57]:
y_pred=model.predict(X_test)
accuracy_score(y_test,y_pred)

0.7906316536550745

In [58]:
confusion_matrix(y_test,y_pred)

array([[942,  94],
       [201, 172]], dtype=int64)

In [59]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.82      0.91      0.86      1036
           1       0.65      0.46      0.54       373

    accuracy                           0.79      1409
   macro avg       0.74      0.69      0.70      1409
weighted avg       0.78      0.79      0.78      1409

